---
# this is a demo of how the user commands work and how to reference salted passwords
# in vars sections.  You could also use vars_files if you like (see other examples)

- hosts: all
  gather_facts: false
  
  tasks:

    - name: Adding user
      user: name={{ username }} password={{ password }}

    